type EquipmentInfo {
  name: String
  location: String
}

type DeviceData {
  mac: String!
  temp_1: Float!
  temp_2: Float!
  rssi: Float!
  date: String!
  compressor_buffer: String!
  evap_fan_buffer: String!
  defrost_buffer: String!
  open_door_buffer: String!
}

type Metrics {
  averageTemperatureByHour: Float
  averageTemperatureByDay: Float
  activeCompressorTime: String
  activeEvaporatorTime: String
  activeDefrostTime: String
}

type Query {
  getDeviceData(mac: String!): DeviceData
  getEquipmentInfo(mac: String!): EquipmentInfo
  getMetrics(mac: String!, startTime: DateTime!, endTime: DateTime!): Metrics
}
